/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as RecitersRouteImport } from './routes/reciters'
import { Route as ReadRouteImport } from './routes/read'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiAudioProxyRouteImport } from './routes/api/audio-proxy'
import { Route as ApiAiCorrectRouteImport } from './routes/api/ai-correct'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const RecitersRoute = RecitersRouteImport.update({
  id: '/reciters',
  path: '/reciters',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioProxyRoute = ApiAudioProxyRouteImport.update({
  id: '/api/audio-proxy',
  path: '/api/audio-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCorrectRoute = ApiAiCorrectRouteImport.update({
  id: '/api/ai-correct',
  path: '/api/ai-correct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/hadith': typeof HadithRoute
  '/prayer': typeof PrayerRoute
  '/read': typeof ReadRoute
  '/reciters': typeof RecitersRoute
  '/training': typeof TrainingRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-correct': typeof ApiAiCorrectRoute
  '/api/audio-proxy': typeof ApiAudioProxyRoute
  '/api/geocode': typeof ApiGeocodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/hadith': typeof HadithRoute
  '/prayer': typeof PrayerRoute
  '/read': typeof ReadRoute
  '/reciters': typeof RecitersRoute
  '/training': typeof TrainingRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-correct': typeof ApiAiCorrectRoute
  '/api/audio-proxy': typeof ApiAudioProxyRoute
  '/api/geocode': typeof ApiGeocodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/hadith': typeof HadithRoute
  '/prayer': typeof PrayerRoute
  '/read': typeof ReadRoute
  '/reciters': typeof RecitersRoute
  '/training': typeof TrainingRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-correct': typeof ApiAiCorrectRoute
  '/api/audio-proxy': typeof ApiAudioProxyRoute
  '/api/geocode': typeof ApiGeocodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/hadith'
    | '/prayer'
    | '/read'
    | '/reciters'
    | '/training'
    | '/api/ai-chat'
    | '/api/ai-correct'
    | '/api/audio-proxy'
    | '/api/geocode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/hadith'
    | '/prayer'
    | '/read'
    | '/reciters'
    | '/training'
    | '/api/ai-chat'
    | '/api/ai-correct'
    | '/api/audio-proxy'
    | '/api/geocode'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/hadith'
    | '/prayer'
    | '/read'
    | '/reciters'
    | '/training'
    | '/api/ai-chat'
    | '/api/ai-correct'
    | '/api/audio-proxy'
    | '/api/geocode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  HadithRoute: typeof HadithRoute
  PrayerRoute: typeof PrayerRoute
  ReadRoute: typeof ReadRoute
  RecitersRoute: typeof RecitersRoute
  TrainingRoute: typeof TrainingRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiCorrectRoute: typeof ApiAiCorrectRoute
  ApiAudioProxyRoute: typeof ApiAudioProxyRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reciters': {
      id: '/reciters'
      path: '/reciters'
      fullPath: '/reciters'
      preLoaderRoute: typeof RecitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio-proxy': {
      id: '/api/audio-proxy'
      path: '/api/audio-proxy'
      fullPath: '/api/audio-proxy'
      preLoaderRoute: typeof ApiAudioProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-correct': {
      id: '/api/ai-correct'
      path: '/api/ai-correct'
      fullPath: '/api/ai-correct'
      preLoaderRoute: typeof ApiAiCorrectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  HadithRoute: HadithRoute,
  PrayerRoute: PrayerRoute,
  ReadRoute: ReadRoute,
  RecitersRoute: RecitersRoute,
  TrainingRoute: TrainingRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiCorrectRoute: ApiAiCorrectRoute,
  ApiAudioProxyRoute: ApiAudioProxyRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
